name: Elixir
on: [push, pull_request]
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: "1.10.4"
          otp-version: "23.1"
      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Install dependencies
        run: make deps
      - name: Run tests
        run: make test
      - name: Generate coverage report and send it to Codecov
        run: make coverage-ci
      - name: Check code formatting
        run: make check-format
      - name: Run static code analysis with Credo
        run: make credo
      - name: Restore Dialyzer cache
        uses: actions/cache@v2
        with:
          path: priv/plts
          key: ${{ runner.os }}-dialyzer-1.10.4-23.1-${{ hashFiles('**/priv/plts/dialyzer.plt.hash') }}
          restore-keys: ${{ runner.os }}-dialyzer-1.10.4-23.1-
      - name: Run static analysis with Dialyzer
        run: make dialyzer
